---
- name: Install Docker, Build Docker Image, and Run Container
  hosts: localhost
  become: yes  # Run tasks as sudo

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
      become: yes

    - name: Add current user to the docker group
      user:
        name: "{{ lookup('env', 'USER') }}"
        groups: docker
      become: yes

    - name: Restart docker service
      systemd:
        name: docker
        state: restarted
      become: yes

    - name: Build Docker Image
      command: "docker build -t python:latest ./Final-Project/Dockerfile"
      become: yes

    - name: Run Docker Container
      command: "docker run -d --name python -p 5000:5000 python:latest"
      become: yes

