# .github/actions/build-and-publish/action.yml
name: 'Build and Publish Docker Image'
description: 'Builds a Docker image and publishes it to GitHub Container Registry'

inputs:
  APP_PASS:
    description: 'Application password'
    required: true
  APP_DB_IP:
    description: 'Database IP address'
    required: true
  APP_TEST_DB:
    description: 'Test database name'
    required: true
  APP_PROJECT_ID:
    description: 'Project ID'
    required: true
  APP_DB_INSTANCE:
    description: 'Database instance name'
    required: true
  TOKEN:
    description: 'TOKEN'
    required: true 

runs:
  using: 'composite'
  steps:
    - run: docker build -t ghcr.io/mohamad0880218/python:latest .
      shell: bash  # or 'pwsh' for PowerShell

    - id: Login_to_GitHub_Container_Registry
      run: echo ${{ inputs.TOKEN }} | docker login ghcr.io -u mohamad0880218 --password-stdin
      shell: bash  # or 'pwsh' for PowerShell

    - id: Testing_image
      run: docker run -d --env-file ./instance/.env2 -p 5000:5000 --name python ghcr.io/mohamad0880218/python:latest
      shell: bash
      
    - id: Kill_container
      run: docker kill python
      shell: bash
      
  
      
    - id: Push_Image
      run: docker push ghcr.io/mohamad0880218/python:latest
      shell: bash 
