name: Code testing with automated build checks and unit tests 
 
on:
  push:
   # branches: [ "master" ]
  pull_request:
   # branches: [ "master" ]

jobs:
  APPLICATION_TESTING: 
  
    runs-on: ubuntu-latest
    env:
      PASSWORD: ${{ secrets.APP_PASS }}
      PUBLIC_IP_ADDRESS: ${{ secrets.APP_DB_IP }}
      DBNAME: ${{ secrets.APP_TEST_DB }}
      PROJECT_ID: ${{ secrets.APP_PROJECT_ID }}
      INSTANCE_NAME: ${{ secrets.APP_DB_INSTANCE }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install flake8 pytest Flask  numpy app xmlrunner flask_sqlalchemy flake8 pymysql
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest testt.py
     
  CREATING_PUBLISHING_IMAGE:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      run: |
        
        sudo apt-get install curl
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Building image
      run: |
        #docker push ghcr.io/mohamad0880218/python:latest
        docker build -t ghcr.io/mohamad0880218/python:latest .
        #docker push ghcr.io/mohamad0880218/python:latest
    - name: Testin image 
      run: |
        docker run -d \
          -e PASSWORD="Root_User" \
          -e DBNAME="testappdb" \
          -e PUBLIC_IP_ADDRESS="34.171.123.44" \
          -e PROJECT_ID="grounded-pager-400600" \
          -e INSTANCE_NAME="my-sql" \
          -p 7000:5000 \
          --name python ghcr.io/mohamad0880218/python:latest

  

    
    - name: PUSH THE PACKAGE
      run: |
        docker stop python
        docker rm python
        docker push ghcr.io/mohamad0880218/python:latest
