name: Docker Image CI

on:
  push:
   # branches: [ "master" ]
  pull_request:
   # branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
          DOCKER_TOKEN: ${{ secrets.GIT_TOKEN }}
          DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      run: echo $DOCKER_TOKEN | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Pulling images from package
      run: |
        
        docker build -t ghcr.io/mohamad0880218/python:latest .
        docker run -v ./:/Final-Project/Artifact -d -p 7000:5000 --name python ghcr.io/mohamad0880218/python:latest
        docker stop python
        docker rm python
        docker push ghcr.io/mohamad0880218/python:latest
