name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Pulling images from package
      run: |
        docker build -t ghcr.io/mohamad0880218/python:latest .
         # docker pull ghcr.io/mohamad0880218/python:latest
        docker run -v ./:/Final-Project/Artifact -d -p 7000:5000 --name python ghcr.io/mohamad0880218/python:latest
        docker stop python
        docker rm python
     # run: |
      #  echo pass=${{ secrets.TOKEN }}
     #   docker login ghcr.io --username mohamad0880218 --password pass

         
    #- name: Build Docker image
      #run: |
        #docker build -t ghcr.io/mohamad0880218/python:latest .
        #docker push ghcr.io/mohamad0880218/python:latest
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@main
      with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: grounded-pager-400600

    - name: Configure gcloud CLI
      run: gcloud config set project grounded-pager-400600

    - name: Build and Push Docker Image
      run: |
         docker build -t gcr.io/grounded-pager-400600/python-app:latest .
         docker push gcr.io/grounded-pager-400600/python-app:latest
    
