# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - production-final-project

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f719aefcd0034ca5ad7120edd8bad7f9 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9314054701b94e81adb5ee2d6ca03df0 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_f719aefcd0034ca5ad7120edd8bad7f9 }}/mohamad0880218/python:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'production-final-project'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fae081c63481437fa6d98d177d3aa049 }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_f719aefcd0034ca5ad7120edd8bad7f9 }}/mohamad0880218/python:${{ github.sha }}'