name: Production-environment

on:
  push:
    branches: [ "master" ]
  pull_request:
     branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: production
    env:
      password: ${{ secrets.GITHUB_TOKEN }}
      username: ${{ github.actor }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    
    - name: Update
      run: |
        sudo apt-get update
        sudo apt-get install -y curl python3 python pip
    - name: Install dependencies
      run: |
        pip install --upgrade pip
    

    - name: Install Ansible
      run: |   
        pip install ansible requests 
    - name: Update Again
      run: |
        sudo apt-get update
    - name: Run Ansible Playbook
      run: |
        ansible-playbook ConfigScript/ProductionAnsible.yml
    
    
      env:
        ANSIBLE_HOST_KEY_CHECKING: "False"
