name: Ansible Workflow
 
on:
  push:
    branches: [ "master" ] # Change this to your main branch

jobs:
  deploy:
    runs-on: ubuntu  # Use a self-hosted runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    

    - name: Install Ansible
      run: |
   
        pip install ansible

    - name: Install Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible

    - name: Run Ansible Playbook
      run: ansible-playbook ConfigScript/ansible.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: "False"

