name: Ansible Workflow
 
on:
  push:
    branches: [ "master" ] # Change this to your main branch

jobs:
  deploy:
    runs-on:  ubuntu-20.04  # Use a self-hosted runner
    env:
      password: ${{ secrets.GIT_TOKEN }}
      username: ${{ github.actor }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Update
      run: |
        sudo apt-get update
        sudo apt-get install -y python pip

    

    - name: Install Ansible
      run: |   
        pip install ansible requests 

    - name: Run Ansible Playbook
      run: ansible-playbook ConfigScript/ansible.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: "False"

