name: Ansible Workflow
 
on:
  push:
    branches: [ "master" ] # Change this to your main branch

jobs:
  deploy:
    runs-on: linux-runner  # Use a self-hosted runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python 3
      uses: actions/setup-python@v3
      with:
        python-version: "3.9.2"

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Run Ansible Playbook
      run: ConfigScript/ansible.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: "False"

