name: TestingEnvironment
 
on:
  push:
    branches: [ "master" ] # Change this to your main branch

jobs:
  Testing:
    runs-on:  production  # Use a self-hosted runner
    env:
      password: ${{ secrets.GITHUB_TOKEN }}
      username: ${{ github.actor }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Update
      run: |
        sudo apt-get update
        sudo apt-get install -y python pip

    

    - name: Install Ansible
      run: |   
        pip install ansible requests 
    - name: Update Again
      run: |
        sudo apt-get update

    - name: Run Ansible Playbook
      run: ansible-playbook ConfigScript/ansible.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: "False"

